spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: VMware1
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
